fear:added my blog post:Jardon237
Developer-Student-Clubs-UBa/blog-posts pull request #17
Opened 2022-10-02 17:11 UTC by Jardon237

which django version is important to use

2022-10-02 17:13 UTC, Burnleydev1 approved these changes

2022-10-02 17:15 UTC, yokwejuste requested changes

2022-10-02 17:15 UTC, yokwejuste commented on blogs/Jardon237.json
> +    "Author": "Ngwa Jude"
```suggestion
    "Author": "Matt Layman"
```

2022-10-03 01:28 UTC, yokwejuste reviewed
I think you're not the author of this blog post, change it to the name suggested!

2022-10-03 05:49 UTC, Burnleydev1 approved these changes

2022-10-03 05:52 UTC, spykelionel approved these changes

2022-10-03 05:54 UTC, merged