feat: added my blog post: joelfah
Developer-Student-Clubs-UBa/blog-posts pull request #3
Opened 2022-10-02 07:32 UTC by Joel-Fah

2022-10-02 10:06 UTC, spykelionel requested changes

2022-10-02 10:06 UTC, spykelionel commented on README.md
> +<br>
Pouvez-vous creer un nouvelle Pull Request pour cela?
Merci

2022-10-02 10:06 UTC, spykelionel commented on README.fr.md
> +# Publication de blogs
Thanks for translating

2022-10-02 10:25 UTC, Joel-Fah commented on README.md
> +<br>
A vrai dire je pensais que ça allait créer une autre. C'est possible d'avoir les étapes à suivre?

Merci.

2022-10-02 12:27 UTC, yokwejuste commented on README.md
> +<br>
Essaie de faire une nouvelle branche pour avoir des PR differentes

2022-10-03 05:59 UTC, spykelionel approved these changes

2022-10-03 07:17 UTC, Burnleydev1 approved these changes

2022-10-03 07:17 UTC, merged